### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Phyks** [Phyks/ampache_react#16]
Major next steps:
- [ ] Handle more formats, through Aurora or transcoding in the API.
- [ ] FilterBar and search, as discussed in #8 
- [ ] Bug fixes and design for the already implemented components.

Global TODO list:
- [ ] Webplayer
  - [x] Using previous and next buttons and going outside of the playlist
    breaks things.
  - [x] Show song duration somewhere.
  - [ ] Webplayer should be pushed at the bottom of the sidebar.
  - [ ] Volume control.
  - [ ] Random / repeat (single song) modes are not yet implemented.
  - [x] Playlist view should be reworked.
  - [ ] Seeking in a song is not exposed in the UI.
  - [x] When playing a song, webplayer does not automatically play the next
    one when reaching the end of the song.
  - [ ] Supported formats (Aurora, errors etc). Update: implemented basic error notification.
- [ ] Discover page
- [ ] Homepage
- [ ] Settings
- [ ] Design

**Comment by Phyks** [comment]
- [x] AlbumPage is not working, should be a scrolled ArtistPage.
  Update: Done as such, except for scroll.

**Comment by Phyks** [comment]
- [ ] Drag & Drop playlist
- [x] Clear playlist button

Bugs:
- [x] On playlist page, play should play specified item, not replace the playlist.
- [x] Play next should not be on playlist page.
- [x] No error message if played song cannot be found.
- [x] If playlist is empty, should display it on /playlist
- [x] Wrong albums linked in SongsTable
- [ ] Max width on track number column in SongsTable
- [ ] More compact play / play next buttons
- [ ] Replace "Filtrer…" with a random artist name
- [ ] Responsive view
- [ ] Placeholders used as labels on login form

**Comment by Phyks** [comment]
Closing and using a milestone to track issues instead, will be more comfortable.
