### ISSUE TITLE
CSS TODO list

### ISSUE THREAD

**Issue by Phyks** [Phyks/ampache_react#6]
- [x] Sidebar hamburger menu
- [x] Spinning wheel during loading: http://fontawesome.io/examples/#animated
- [x] Nicer alerts when an API error occurs
